# Generated by Django 3.2.7 on 2021-09-10 19:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('favorites', models.ManyToManyField(to='products.Products')),
            ],
        ),
    ]
